self.lock() should simulate a poisoned lock scenario to trigger the Err(_) branch, return type must be Result<S::Ok, S::Error>
